### ISSUE TITLE
Feral Druid - Rake

### ISSUE THREAD

**Issue by mikevaleriano** [AdiAddons/AdiButtonAuras#296]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.17

#### How did you install the addon (curse client/manually)?
Curse

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Release

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Druid
  - Your spec: Feral
  - Name of the spell (and spell id if known): Rake
  - Source of the spell (core ability/talent/artifact/pvp): Core

Timer won't show, that's it. In config it says enabled, but no timer. Other bleeds working perfectly.

**Comment by Rainrider** [comment]
Can't reproduce sadly. The debuff id is 155722, the spell id is 1822. Could you confirm this for me please, maybe some talents modify those and I didn't notice it.

**Comment by Rainrider** [comment]
Do you have a macro for Rake? If so, please post it here.

**Comment by Rainrider** [comment]
ABA fails to pick a target because of the macro. It would work without the macro. I screwed this up with https://github.com/AdiAddons/AdiButtonAuras/commit/97058bc839ea686f3444dbcdbd4ef823a3fd0830.
I'll try to look into it this weekend, but can't promise :( Sorry about that.

**Comment by Rainrider** [comment]
Duplicate to #295

**Comment by Rainrider** [comment]
@mikevaleriano 86ab7362694c8b8f27bd585054e5cffd04b5fa1b should fix the problem. A release will be up on twitch/curse in a few minutes.

**Comment by mikevaleriano** [comment]
I just updated via twitch to version 2.0.18, and the problem continues, as shown below.

Thrash is tracked (yellow), Rake still isn't (red). Only in the same macro, works fine in the direct ability button.

![image](https://user-images.githubusercontent.com/6718750/43349790-bdae7c54-91d8-11e8-8ce2-0f36fe821c7e.png)

**Comment by Rainrider** [comment]
![wowscrnshot_072818_013958](https://user-images.githubusercontent.com/363876/43350475-be4be10e-9207-11e8-9ad0-b2acb9cd147e.jpg)

**Comment by mikevaleriano** [comment]
After a clean reinstall (I had previously updated) it's working. Thanks so much!
