### ISSUE TITLE
Warrior Battle Shout Rule "Show the number of group members missing Battle Shout" shows raid numbers after leaving raid group

### ISSUE THREAD

**Issue by wsuhoey** [AdiAddons/AdiButtonAuras#309]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.21

#### How did you install the addon (twitch client/manually)?
Twitch

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Release

#### Which type of installation did you choose (nolib/normal)?
Unchecked "Install Libraries Separately"

Warrior Battle Shout Rule "Show the number of group members missing Battle Shout" shows raid numbers after leaving raid group.

I have the following settings for Battle Shout:

Show missing: Show Flash
Show missing threshold: 0
Rules: Show the number of group member missing Battle Shout: Checked

If I'm in a raid group, and there are members without Battle Shout, it of course has a number there (say, 16, for example).
Then, after leaving the Raid Group, the number shown is still 16.
If I cast Battle Shout to try to clear this number, it still shows 16.

So, AdiButtonAuras should probably reset, clear, or re-update the missing group members number upon group changes (including Instance Groups and regular Party groups).

**Comment by Rainrider** [comment]
> If I cast Battle Shout to try to clear this number, it still shows 16.

I pushed some changes to address this, however the quoted statement seems strange. Could you please test with version 2.0.22 and share your results?

**Comment by wsuhoey** [comment]
I was finally able to try this out today.
Even with 2.0.22, the issue persists; the group member number count (of those missing Battle Shout) still shows the same number after leaving a raid group.
In Legion, this wasn't an issue, incidentally.

**Comment by Rainrider** [comment]
There were no group buffs in Legion :) This is strange however, I'll need some time to investigate.

**Comment by Rainrider** [comment]
While I found a bug with the rule (it counts party and raid pets too), I can't confirm that the counter does not refresh when you exit a party. It displays 1 if you are missing the buff even when you are not in a group and updates accordingly when players leave or join. Maybe you have a custom rule there or something.

**Comment by wsuhoey** [comment]
Well, I meant during the 8.0 pre-patch timeframe. It worked during that timeframe and broke when BFA went live.

Regarding your repro, were you in a raid group where it showed the missing buffs, THEN left the group and it showed 1 instead of the raid number?

**Comment by Rainrider** [comment]
I tried to reproduce with an LFG dungeon group. The number of missing buffs updated correctly both when other players and I joined/left. I don't see why a raid should be any different unless GROUP_ROSTER_UPDATE does not fire when you leave a raid (this is the event ABA uses to update group units).

I haven't tried your settings though (missing flash and missing threshold) but those should be irrelevant for the count. I'll try it out just in case.

**Comment by wsuhoey** [comment]
Can you try to repro by leaving an actual raid group (not just a 5-man group)? The issue manifests when leaving a raid group, such as via world quest group finder for a world boss.

is GROUP_ROSTER_UPDATE a Blizzard function or ABA custom function?

If you need more info from me, (addons list or whatever) please tell me.

**Comment by Rainrider** [comment]
Tested in a raid too, can't reproduce.

**Comment by wsuhoey** [comment]
What are the next steps for troubleshooting?

**Comment by Rainrider** [comment]
TBH I don't have any idea what may be causing this. I don't see how other addons may be interfering, but you could try to reproduce it with all other addons disabled. You may also close the game and wipe ABA's settings (simply move <wow folder>\WTF\Account\<your account name>\SavedVariables\AdiButtonAuras.lua to another folder) to check if this is causing it. Other than that I'm out of guesses.

**Comment by wsuhoey** [comment]
I tried renaming my AdiBurttonAuras.lua in saved variables so that it re-generates it, but the issue still persists.... :/

Another thing I noticed is that the count doesn't seem to consider combat pets like hunter and warlock pets.

**Comment by Rainrider** [comment]
Have you tried disabling the rule to see if something else displays something on that button?

**Comment by wsuhoey** [comment]
Disabling the rule does not show any group count numbers. The only number being displayed is the cooldown timer.

**Comment by wsuhoey** [comment]
Additionally, even with the Rule disabled, having the spell set to `Show missing = Show flash` is erroneously flashing even if I have the buff, with 50+ minutes remaining even. This flash border appears after the 15-second cooldown timer completes.

**Comment by Rainrider** [comment]
Yeah, disabling all rules does not disable the button which is kind of strange maybe. But this is unrelated to this issue.

You have not by any chance modified your copy of ABA, have you?

**Comment by wsuhoey** [comment]
I have not modified the LUA code of my copy of ABA, if that's what you mean.
At most, the modifications i've made are settings such as flash when missing, etc.

Here's the troubleshooting steps I've done today:
1. I've disabled all add-ons except AdiButtonAuras and AdiButtonAuras - Configuration.
2. Checked (enabled) the "Show the number of group members missing Battle Shout" rule.
3. Joined a raid (world boss Matriarch Ji'arak).
4. Cast Battle Shout. It displays a non zero number.
5. Leave the raid.
6. Issue persists: The same non-zero number is still displayed.

My next troubleshooting steps I've done are to completely manually delete both AdiButtonAura addon folders, and all  AdiButtonAuras saved variables, and to re-install via Twitch.

We'll see if the issue still persists...

**Comment by Rainrider** [comment]
Thanks a lot for your persistence. Btw could you confirm that the buff applied by Battle Shout has the spell id 6673?

**Comment by wsuhoey** [comment]
I'm sad to report that the bug I'm experiencing still persists, and it's not limited to raid groups.

I was in a group of 4. Casted Battle Shout, it showed 2. I left the group. The number immediately changed to 4, even though I was alone.

How do I tell the spell id? It doesn't seem to indicate what it is when I se
